ONSdigital/census-rm-ddl

manual_scripts/0005-modify-receipt-received-column.sql

The column doesn't not exist before running these migrations so this script needs to add the column rather than attempting to modify it.
* Amend migration 0005 to create the receipt_received column in actionv2.cases
Run through the migrations in an environment in the state of prod after the unaddressed print run.
https://trello.com/c/NHLG59GN/1014-bug-migration-scripts-never-create-actionv2cases-receiptreceived-column
https://trello.com/c/ArDwE6ru/930-run-book-for-sample-load-phase-1-13

Amend migration 0005 to create the receipt_received column

---

manual_scripts/0009-add-invalid-address-column.sql

Fieldwork might discover that an address is not valid and notify RM via a message. We need to handle that message so that we cease doing follow-up actions and we know why we haven't had a response.
New DB column.
Run the script in an existing DB.
Trello: https://trello.com/c/bKxycLe3

Add manual script for address_invalid column

---

manual_scripts/0008-add-case-type-column.sql

Add new Case Type column to Case Processor and Action scheduler cases tables.  
This will allow RM to differentiate a Household case from a Household individual PQ case.
SQL script to add column and set existing cases to 'HH'.
Run script in Docker Dev.
https://trello.com/c/gUMjDkBu/1064-create-case-type-variable-to-differentiate-hh-and-hi-as-opposed-to-address-type-5

Add case type column to cases tables.

---

manual_scripts/0010-add-undelivered-as-addressed-column.sql

QM (Leidos) and PPO (Royal Mail) will receive email that is undeliverable - undelivered as addressed - and they will notify RM. We need to send a message to Field so that the cases can be followed up and we can find out why the mail couldn't be delivered.
Added undelivered_as_addressed column to case tables
Run the acceptance tests, along with Action Scheduler, Case API, Pubsub and Case Processor on the same branch (`undelivered-as-addressed`) along with census-rm-docker-dev.
Trello: https://trello.com/c/HOWUDNMR

Add script to add undelivered_as_addressed column to case tables

---

manual_scripts/schema_and_data_migration/0012-add-rm-dev-group-role.sql

We need a group role for RM developer database access
* Add DDL script to create rm developer group role
Run the new DDL script in your environment, create a user and grant them the new rm_developer group role with `GRANT rm_developer TO <user>;`. Connect as this user and you should be able to perform all the operations we might need to for ops support.
https://trello.com/c/Ey6fluwI/1228-create-ddl-to-add-rmdev-group-role-with-required-permissions-so-dev-db-accounts-can-be-created-given-appropriate-access

DDL script to create rm developer group role

---

manual_scripts/schema_and_data_migration/0013-add-unique-constraint-case-id.sql

Case IDs need to be unique in our case tables so that we can throw an error if we receive duplicate messages (e.g. from a CCS request message).
* Remove unique constraint (which removes the associated index) on `action.cases` table
* Remove existing, non-unique index on `casev2.cases` table.
* Alter `actionv2.cases` and `casev2.cases` tables to add a unique constraint.
Run the SQL against your DB. Publish CCS message (see acceptance tests for an example msg) with the same case ID more than once. The case-processor should correctly log that the case ID unique constraint is violated.
https://trello.com/c/UfX9Ibig/1270-add-a-unique-constraint-to-the-caseid-column-in-casev2cases-table-3

Add case ID unique constraint

---

manual_scripts/action_plans_and_rules/0004-woc-update-trigger-dates-for-reminder-letters.sql

The date on 3 previously created action rules was incorrect.  This is to update them to the correct dates.
New script to update the trigger dates for 3 action rules that have already been created.  Note - 28th Oct is GMT so the 6:00am UTC start time in the script is correct.
Trello card: https://trello.com/c/HO6Lf1cB

Update trigger date on previously created WoC action rules

---

groundzero_ddl/actionv2.sql
groundzero_ddl/casev2.sql

As part of CCS refactoring, the `ccs_case` column has been removed and a more generic `survey` column has been added.  Note - the `ccs_case` column is still required in the uac_qid_link table.
https://trello.com/c/4gq2Ufvz

Remove ccs_case column and add survey column

---

groundzero_ddl/actionv2.sql

Survey column shouldn't exist in the actionv2.cases table as it isn't in the model in action processor.  It was added by mistake.
Removed the survey column from actioinv2.cases.
Run the ground zero script then check that the acceptance tests pass.

Remove survey column from actionv2 ground zero script

---

groundzero_ddl/casev2.sql

case-processor and case-api are failing to start in the performance test environment due to the last_updated column not being present.
Added last_updated to groundzero script.

Add last_updated column to ground zero script

---

groundzero_ddl/actionv2.sql
groundzero_ddl/casev2.sql
patches/300_drop_column_state_from_cases.sql

We can now safely remove the redundant case `state` column from our schemas
Added patch and updated ground zero
Make sure tests and acceptance tests still pass from the links below
https://trello.com/c/dBJe87ZS/481-get-rid-of-casestate-from-case-table-8
https://github.com/ONSdigital/census-rm-case-processor/pull/101
https://github.com/ONSdigital/census-rm-case-api/pull/53
https://github.com/ONSdigital/census-rm-action-scheduler/pull/64
https://github.com/ONSdigital/census-rm-action-worker/pull/9
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/169

Remove case state

---

groundzero_ddl/rebuild_from_ground_zero.sh

The location of the groundzero script was wrong and broke in the pipeline.
- Fixed groundzero location
- Create a ddl pod in your GCP environment with this pr. 
- You can test this by creating a pod in your environment and trying to run `kubectl exec census-rm-ddl -- /bin/bash groundzero_ddl/rebuild_from_ground_zero.sh`. Should destroy the schemas and rebuild them.

fixed rebuild_from_groundzero script

---

.github/PULL_REQUEST_TEMPLATE.md
groundzero_ddl/actionv2.sql
groundzero_ddl/casev2.sql
groundzero_ddl/ddl_version.sql
patches/700_add_new_hand_delivery_column_to_action_schema.sql

We need to add `handDeliver` bool flag on each of our outgoing Action Instruction `CREATE` messages to Field. 
* Updated actionv2.cases to hold the flag
* Added comma casev2.cases in ground zero 
Run the scheme
https://trello.com/c/774V6fGU/580-add-handdelivery-flag-to-casecreated-and-caseupdated-events-and-case-api-8
https://github.com/ONSdigital/census-rm-fieldwork-adapter/pull/30
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/191
https://github.com/ONSdigital/census-rm-action-worker/pull/10
https://github.com/ONSdigital/census-rm-case-processor/pull/112
https://github.com/ONSdigital/census-rm-action-scheduler/pull/65

RMC-317: Add hand delivery on outbound msgs

---

Pipfile.lock
groundzero_ddl/ddl_version.sql

The groundzero script now creates now schema as its rebuilding it so theres no need for the create schema to be in the ddl_version.sql
- removed `create schema` from ddl_version.sql
- run the rebuild groundzero script and it should recreate them all successfully

Remove create schema from ddl_version.sql

---

groundzero_ddl/casev2.sql
groundzero_ddl/ddl_version.sql
patches/1400_add_timestamps_to_uacqidlink.sql

We needed created & updated timestamps on the UAC QID Link table, so that we can send any updated rows to DAP via the data export process, which only sends daily deltas.
Added new columns for created & updated to UacQidLink table.
Run an acceptance test which updates a UAC QID link and make sure the updated timestamp is correctly updated, and the created timestamp remains unchanged.
Trello: https://trello.com/c/91vLJAO8

Add created and updated timestamps to uacqidlink table

---

groundzero_ddl/casev2.sql
groundzero_ddl/ddl_version.sql
patch_database.py
patches/1600_add_extra_case_event_and_uacqid_indexes.sql

Case API was performing very badly when retrieving case events.
Added indexes to both `uac_qid_link` and `event` table to prevent table-scanning.
Load large sample. Call case API including `?caseEvents=true`. It should be fast response time.
Trello: https://trello.com/c/fHPtdl59

Add missing indexes to improve performance

---

build_groundzero_ddl.sh
groundzero_ddl/ddl_version.sql
groundzero_ddl/destroy_schemas.sql
groundzero_ddl/exceptionmanager.sql
groundzero_ddl/rebuild_from_ground_zero.sh
patch_database.py
patches/1700_create_exceptionmanager_schema.sql
pom.xml

For speed of development during the rehearsal, we didn't make the Exception Manager persistent. We now need to have the service backed by a persistent data store instead of using a Rabbit queue to save the quarantined messages.
Added persistence.
Publish a bad message onto a Rabbit queue. Quarantine the bad message. Check the `exceptionmanager` database.
Trello: https://trello.com/c/sYuR2Vgw

Persist quarantined messages

---

groundzero_ddl/actionv2.sql
groundzero_ddl/ddl_version.sql
patch_database.py
patches/2100_fancy_new_fulfilment_to_send_table.sql

The refactored Action services use a new table called `fulfilment_to_process` and the old one is dead.
Create the table. Patch if necessary.
Zero regression.
Trello: https://trello.com/c/OyqQnLqX

Migrate to new fulfilment_to_process table

---

groundzero_ddl/ACTION-ddl_version.sql
groundzero_ddl/actionv2.sql
patch_database.py
patches/action/300_rename_action_type_column_to_fulfilment_type.sql

Using the _action_ type for fulfillments was super confusing in the code, so I created a new enumeration for the non-actions (i.e. fulfillments) and the database should reflect that change.
Renamed `action_type` to `fulfilment_type` in the `fulfilment_to_process` table.
Reminder: Make you have run `build_groundzero_ddl.sh` and not manually edited the ground zero DDL.
Try it in your DB.
Trello: https://trello.com/c/J1Gr5PNq

Rename action_type column to fulfilment_type

---

groundzero_ddl/casev2.sql
groundzero_ddl/ddl_version.sql
patch_database.py
patches/main/2600_add_index_on_postcode.sql

The first feature needed for ops-ui is to be able to search for cases via a postcode. This PR adds a index on the postcode column in the cases table
- Added index on the postcode column
- Run with the other branches on the ticket
- Try searching for cases on ops-ui
- Run the ATs
[Trello](https://trello.com/c/qkkjvupd)

Add index on postcode

---

README.md
groundzero_ddl/casev2.sql
groundzero_ddl/ddl_version.sql
manually_applied_indexes.sql
patch_database.py
patches/main/2700_remove_index_on_postcode.sql

The index on the postcode column alone did not aid the postcode search queries.
* Delete postcode index
* Add manually applied indexes script
* Add postcode search index to manual indexes
* Update README
Reminder: Make you have run `build_groundzero_ddl.sh` and not manually edited the ground zero DDL.
Check the scripts
https://trello.com/c/fg58euQh/1361-add-a-fancy-pants-index-on-postcode-column-to-speed-up-rops-query-time

Manually applied postcode search index

---

groundzero_ddl/rebuild_from_ground_zero.sh

The rebuild_from_ground_zero.sh script is hardcoded to use "password", this makes it a bit of a pain when running it against non-dev envs
changed rebuild_from_ground_zero.sh so you can pass a "PASSWORD" var or it will default to using password like it did before
- run the ddl pod in your test env
- rebuild_from_ground_zero.sh and it should run fine
- change the db password to something else and run PASSWORD=<you new db password> rebuild_from_ground_zero.sh

fix rebuild script to use PASSWORD var or default to "password"

---

groundzero_ddl/ddl_version.sql
groundzero_ddl/exceptionmanager.sql
patch_database.py
patches/main/2900_new_exception_rule_attributes.sql

Sometimes, the 3 retries with a 1-second delay is inadequate, and we end up logging and raising an exception with the exception manager. This could be really annoying during the Census, because it will generate a lot of noise. When we've been war-gaming, we've seen that a flood of messages can cause exceptions which resolve themselves, due to locking contention, for example.
Implemented a configurable "minimum number of times to see an exception before we log it".
Implemented a filter on the admin API so that it only returns exceptions which have been seen a certain number of times.
ADDENDUM: I kinda went a bit mad and added more features. Can now "throw away" bad messages (silently skip, don't quarantine, don't log). Can suppress all logging (but not skip/quarantine) if logs are getting …

Add new columns for Exception Manager rules

---

groundzero_ddl/ACTION-ddl_version.sql
groundzero_ddl/actionv2.sql
groundzero_ddl/casev2.sql
groundzero_ddl/ddl_version.sql
patch_database.py
patches/action/400_alter_ce_actual_responses_to_be_not_null.sql
patches/main/3000_alter_ce_actual_responses_to_be_not_null.sql

When an AddressTypeChange event occurs where the new address is a CE Case, the ceActualResponses is null rather than 0 
Set column to be not null
Test locally 
https://trello.com/c/DUgevj8y

AddressTypeChange for CE Case ceActualResponses Defaulted to Zero

---

Pipfile
Pipfile.lock
groundzero_ddl/ddl_version.sql
patch_database.py
patches/main/3100_redact_uacs_from_event_payloads.sql

Before we introduced the data redacting into the Case Processor, we were leaking UACs into our event payloads, which we then export to MI and DAP, and which are also visible via the ROps UI. We should redact that data **before** we do the one-off data exports, and before anybody is given access to ROps UI, so that we don't leak these sensitive codes.
Added a data patch to redact the UACs out of the event payloads.
Has been tested in Grey Lodge against realistic data. Results:
```
Info
2021-01-08 14:16:29.380 GMT
>>> BEGIN
Info
2021-01-08 14:20:08.560 GMT
UPDATE 2665450
Info
2021-01-08 14:20:08.586 GMT
COMMIT
Info
2021-01-08 14:22:53.234 GMT
BEGIN
Info
2021-01-08 14:26:23.846 GMT
UPDATE 1483673
Info
2021-01-08 14:26:23.899 GMT …
```

Redact UACs from event payloads before we send to DAP & MI

---

groundzero_ddl/casev2.sql
groundzero_ddl/ddl_version.sql
patch_database.py
patches/main/3200_add_index_on_case_uprn.sql

We need speedy look ups on UPRN for case API, this PR adds an index to facilitate.
* Regenerate groundzero DDL with uprn index
* Add patch script to create index
Reminder: Make you have run `build_groundzero_ddl.sh` and not manually edited the ground zero DDL.
Check the patch SQL runs, regenerate the DDL off the linked case processor branch to verify it doesn't change. 
https://trello.com/c/XWfypxu8/1874-add-indexes-to-uprn-field-in-cases-db-table-5
https://github.com/ONSdigital/census-rm-case-api/pull/104
https://github.com/ONSdigital/census-rm-case-processor/pull/227

1874 Add index to UPRN field in cases table

---

permissions/RM-Support-Action-Permissions.sql
permissions/RM-Support-Permissions.sql

We need a permission level with minimum required for daily/expected run booked tasks. These are copies of the read access permissions but with a couple of specific write/edit/delete perms where required.
* Add main/action support permission definitions 
Reminder: Make you have run `build_groundzero_ddl.sh` and not manually edited the ground zero DDL.
Run the scripts into your dev environment, grant the role to a user and check you can read/edit tables appropriately.
https://trello.com/c/escpI4sW/2018-create-support-db-permission-roles

Add RM support permission definitions
